#-------------------------------
# General Site Settings
title: Joahn
logo: seoseoul.png # You can add own logo.
description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Byeongjun Cho
  image: IMG_1680.JPG
  say-hello: Hello, I’m <strong>Joahn</strong>
  bio: ML/DL, Statistics, Democracy, and talks about <strong>media</strong>, and <strong>cultural economy </strong>. I Love <a href="#">music</a> & swimming.


#-------------------------------
# Contact links
facebook: https://facebook.com/chchchch0000/ # Add your Facebook handle
instagram: https://instagram.com/bleu.ultra/ # Add your Instagram handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: joahn # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: bleu.ultra # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
